# =============================================================================
# cna-template release identity -> the generated header CnaTemplate/Version.hpp.
#
# The single source of truth is project(CnaTemplate VERSION ...) plus
# CNA_TEMPLATE_VERSION_PRERELEASE in the root CMakeLists.txt; this file only
# renders that decision into a header. Nothing else in the tree may hard-code the
# number -- docs/releasing.md lists the hand-maintained copies (CHANGELOG.md,
# README.md) that a release bump must update by hand.
#
# The header is the template's own version, not CNA's: CNA's is CNA/Version.hpp
# (CNA::getVersionString()), generated by CNA from its own project(). A game made
# from this template keeps this mechanism and renames the project; the macros
# and the namespace then still describe the game's release.
# =============================================================================

configure_file(
    "${CMAKE_CURRENT_SOURCE_DIR}/cmake/templates/Version.hpp.in"
    "${CMAKE_CURRENT_BINARY_DIR}/generated/include/CnaTemplate/Version.hpp"
    @ONLY)
